### ISSUE TITLE
Suggestion: Don't bundle emulator

### ISSUE THREAD

**Issue by MartinAnt** [adminteractive/chatbot#5]
Lets remove the emulator from git and reference documentation to use https://github.com/MartinAnt/botframework-emulator-dockerized instead.

This works fine with linux but I have not tested it with Windows or Vagrant. If it doesn't cover windows then we should not remove the emulator from this project.

Todo:
Test with Vagrant

**Comment by ncmalitha** [comment]
yes probably you are right . because its a question if the emulator is a dependency

**Comment by MartinAnt** [comment]
I also thought about the Vagrant and Windows and it's actually pretty obvious that you can't run the emulator within docker container with those because it depends on sharing the host display to the container and it only works with linux (with somekind of desktop manager).

If you want to use it on Windows, then the best thing would be to run the docker solution in a Virtualbox ubuntu with a desktop. I believe you can also have Vagrant box with optional desktop manager but I am not sure about this. 

Anyways running the emulator in docker only works on linux environments atm. If you use windows then you need an alternative solution.

About whether to bundle the emulator or not, I think if everyone agrees, then we should remove it from the codebase and just add instruction to Readme on how to test the app with emulator. How you set up the emulator is a separate issue.

**Comment by ncmalitha** [comment]
yes, agreed
